import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Exemplo, MeuComponente, InputFocus } from "@/components/componentefuncional";
import { TemaProvider, BotaoTema } from "@/components/componentefuncional";
import { useContext } from "react";
import { StoreProvider } from "@/redux/StoreProvider";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body

        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <TemaProvider>
            <Navbar />
            <MeuComponente />
            <InputFocus />
            <Exemplo />
            <BotaoTema />
            {children}
          </TemaProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
